name: "Test pull request code"

on:
  pull_request

jobs:
  run:
    runs-on: ubuntu-20.04  

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      
      # - name: Install Dependencies
      # - uses: borales/actions-yarn@v2.3.0
      #   with:
      #     cmd: install

      # - name: Run test
      # - uses: borales/actions-yarn@v2.3.0
      #   with:
      #     cmd: test
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:cov > OUT; sed -n 6,8p OUT > .github/workflows/COVERAGE_REPORT

      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: COVERAGE_REPORT